/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":list"))

    // Javalin — FilterContext wraps io.javalin.http.Context
    api(libs.javalin.bundle)

    // Resilience4j — circuit breaker + rate limiter
    api(libs.resilience4j.circuitbreaker)
    api(libs.resilience4j.ratelimiter)

    // Jackson — model serialization
    api(libs.jackson.databind)

    // OkHttp — upstream HTTP/WebSocket client
    api(libs.okhttp)

    // Caffeine — in-process cache
    api(libs.caffeine)

    // Logging
    api(libs.slf4j.api)

    // Test
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.junit)
}
