/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    // Javalin — FilterContext wraps io.javalin.http.Context
    api(libs.javalin.bundle)

    // Jackson — model serialization
    api(libs.jackson.databind)

    // Test dependencies
    testImplementation(libs.assertj.core)
}
